version: '3'
services: 
    web:
      image: amazon/amazon-ecs-sample
      ports: 
        - "80:80"
      logging: 
        driver: awslogs
        options:
          awslogs-group: ec2-lesson
          awslogs-region: ca-central-1
          awslogs-stream-prefix: web