Resources: 
  MyInstance: 
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: use-east-1a
      ImageId: ami-0a887e401f7654935
      InstanceType: t2.micro
  MyEIP:
    Type: AWS::EC2::EIP
    Properties: 
      InstanceId: !Ref MyInstance 